---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvit-app-deployment
  namespace: default  # Update this if you have a specific namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvit-app
  template:
    metadata:
      labels:
        app: nvit-app
    spec:
      containers:
        - name: nvit-app
          image: davidokpe/nvit-app:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: nvit-app-service
  namespace: default  # Update this if you have a specific namespace
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: nvit-app
